spring:
  jpa:
    generate-ddl: true
    show-sql: true
    #open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/hbs_db # для запуска БД и приложения в контейнерах, вместо 'localhost' нужно указать имя контейнера - 'postgres'
    username: postgres
    password: postgres
    hikari:
      schema: hbs_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS hbs_schema
      connection-timeout: 10000
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/appdatabase?authSource=admin

  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    registerUserTopic: "register-user-topic"
    bookingRoomTopic: "booking-room-topic"
    statisticGroupId: "statistic-group-id"
  path:
    statisticFile: "C:/Users/alexn/IdeaProjects/hotelbookingservice/statistics.csv"

logging:
  level:
    org:
      apache:
        kafka: info